defaults:
  - model/conv
  - _self_
inputs:
  - tws
  - twa_x
  - twa_y
tuning_inputs: []
outputs:
  - sog
transforms:
  - [normalize, []]
  - [random_flip, [[twa_y], 0.5]]
  - [cut_sequence, [null, -1]]
encoder: null
model:
  path: ""
  force_new_model: false
  # Other parameters are set by the defaults
data:
  path: ""
  train_batch_size: 10000
  test_batch_size: 1000
  training_ratio: 0.9
  shuffle: true
  train_workers: 2
  test_workers: 1
training:
  epoch: 5
  mixed_precision: false
  optim:
    name: adam_w
    learning_rate: 0.01
    scheduler: reduce_plateau
    scheduler_patience: 20
    scheduler_factor: 0.8
    momentum: 0.99
log: pinta_mini
device: "cuda:0"
